### ISSUE TITLE
Use github downloads

### ISSUE THREAD

**Issue by jwillemsen** [yuryfdr/gentoo-overlay#2]
Would recommend to use github as download location, much faster and more bandwidth available.

https://github.com/yuryfdr/gentoo-overlay/blob/7df7f2b0fd94cab79eb811c67421209bfa22a964/dev-libs/ace/ace-7.0.5.ebuild#L9

**Comment by yuryfdr** [comment]
It's good idea, but not solve main problem - build taox11 on top of installed ace (in case when using git is not possible, for examle)

**Comment by jwillemsen** [comment]
Building taox11 on top of an installed ACE/TAO could be done, I only don't know how much work it would be. Given that we are using MPC you should be able to generate the necessary makefiles manually and build it with GNU make, similar to building TAO
